version: "3"

services:
  main:
    build:
      context: .
    ports:
      - ${PORT:-2000}:2000
      - "2022:22"
    volumes:
      - ${WORKSPACE:-./workspace}:/workspace
    shm_size: "32gb"
    restart: always
