version: "3"

services:
  main:
    build:
      context: .
    ports:
      # - {server port}:{docker port}
      - 2000:2000  # to use jupyterlab
      - "2022:22"  # to use vscode
    volumes:
      - ./workspace:/workspace
    restart: always
